/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

public class PharmacyFrame extends javax.swing.JFrame {

    PurchaseFrame pf = new PurchaseFrame(this);
    SaleFrame sf = new SaleFrame(this);

    public PharmacyFrame() {
        initComponents();
        setSize(450, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        purchaseButton = new javax.swing.JButton();
        saleButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(null);

        jLabel1.setText("PHARMACY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 40, 71, 16);

        jLabel2.setText("Please choose the relevant button for the transaction");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 333, 16);

        purchaseButton.setText("NEW PURCHASE TO THE PHARMACY");
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(purchaseButton);
        purchaseButton.setBounds(30, 160, 336, 50);

        saleButton.setText("NEW SALE TO THE CUSTOMER");
        saleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saleButton);
        saleButton.setBounds(30, 230, 336, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/buse/Desktop/CTIS221Project.v1 2 - Copy/CTIS221Project.v1/src/GUI/pharmacy-bag-medicines-blue-shopping-different-medical-pills-bottles-purchases-drugstore-concept-healthcare-objects-168310074.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-70, 0, 620, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
        pf.setVisible(true);
        dispose();
    }//GEN-LAST:event_purchaseButtonActionPerformed

    private void saleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleButtonActionPerformed
        sf.setVisible(true);
        dispose();
    }//GEN-LAST:event_saleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JButton saleButton;
    // End of variables declaration//GEN-END:variables
}
